---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cambod-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: shell 
    scripts:
      - |
        # 1. Create the dconf profile if it doesn't exist
        mkdir -p /etc/dconf/profile
        echo -e "user-db:user\nsystem-db:local" > /etc/dconf/profile/user

        # 2. Create the system-wide default keyboard settings
        mkdir -p /etc/dconf/db/local.d
        cat <<EOF > /etc/dconf/db/local.d/01-multi-keyboard
        [org/gnome/desktop/input-sources]
        sources=[('xkb', 'us'), ('xkb', 'kh')]
        mru-sources=[('xkb', 'us'), ('xkb', 'kh')]
        EOF

        # 3. Update the dconf binary database
        dconf update
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship
        - freeipa-client
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: rpm-ostree
    install:
    - netbird
    - netbird-ui
    - https://github.com/rustdesk/rustdesk/releases/download/1.4.5/rustdesk-1.4.5-0.x86_64.rpm
    - mscore-fonts-all
    - google-noto-sans-khmer-fonts
    - khmer-os-fonts-all
    - ibus-m17n
    - m17n-db
    - curl
    - cabextract
    - xorg-x11-font-utils
    - fontconfig
    - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
  - type: systemd
    system:
      enabled:
        - netbird.service
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.libreoffice.LibreOffice
          #- com.rustdesk.RustDesk
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
